export const Routes = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/sign-up',
    REGISTER_CONFIRMATION: '/sign-up/confirm',
    REGISTER_ON_BOARD: '/sign-up/onboard',
    FORGOT_PASSWORD: '/forgot-password',
    FORGOT_PASSWORD_CONFIRMATION: '/forgot-password/confirmation',
    RESET_PASSWORD: '/reset-password',
    VERIFY_EMAIL: '/email/verify',
    PROFILE: '/profile',
    EDIT_PROFILE: '/edit-profile',
    CHAT: '/chat',
    CALENDAR: '/calendar',
    NOTIFICATIONS: '/notifications',
    SETTINGS: '/settings',
};
