export const Routes = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/sign-up',
  REGISTER_CONFIRMATION: '/sign-up/confirm',
  REGISTER_ON_BOARD: '/sign-up/onboard',
  FORGOT_PASSWORD: '/forgot-password',
  FORGOT_PASSWORD_CONFIRMATION: '/forgot-password/confirmation',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  TEST: '/test',
  SUPPORT: '/support',
  ADD_ACCOUNT: '/add-account',
  ADD_ACCOUNT_ONBOARD: '/add-account/onboard',
  PROFILE: '/profile',
  INVITATIONS: '/invitations',
  INVITATIONS_ONBOARD: '/invitations/onboard',
  INVOICE: '/invoices/:id',
  INVOICE_PAY: '/invoices/:id/pay',
  LOGIN_AS: '/login-as'
}
