export { ReactComponent as AmexIcon } from './amex.svg'
export { ReactComponent as BtcIcon } from './btc.svg'
export { ReactComponent as McIcon } from './mc.svg'
export { ReactComponent as VisaIcon } from './visa.svg'
export { ReactComponent as SecureIcon } from './secure.svg'