name: CI dev
on:
  push:
    branches: [ dev ]
jobs:
   deploy:
    name: "Deploy to dev"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code to allright-frontend-dev server
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.SSH_HOST_DEV }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: 22
         script: |
          cd /home/identity/public_html
          git checkout dev
          git pull origin dev
          cp /home/identity/public_html/.env.example /home/identity/public_html/.env
          yarn install
          yarn build
          
